/*Queries that provide answers to the questions from all projects.*/

SELECT *
FROM ANIMALS
WHERE NAME LIKE '%mon';

SELECT NAME
FROM ANIMALS
WHERE DATE_OF_BIRTH BETWEEN '2016-01-01' AND '2019-12-31';

SELECT NAME
FROM ANIMALS
WHERE NEUTERED = true AND ESCAPE_ATTEMPTS < 3;

SELECT NAME, DATE_OF_BIRTH
FROM ANIMALS
WHERE NAME IN ('Agumon','Pikachu');

SELECT NAME, ESCAPE_ATTEMPTS
FROM ANIMALS
WHERE WEIGHT_KG > 10.5;

SELECT *
FROM ANIMALS
WHERE NEUTERED = TRUE;

SELECT *
FROM ANIMALS
WHERE NOT NAME = 'Gabumon';

SELECT *
FROM ANIMALS
WHERE WEIGHT_KG >= 10.4 AND WEIGHT_KG <= 17.3;
