/* Database schema to keep the structure of entire database. */
CREATE TABLE ANIMALS (
 ID INT,
 NAME VARCHAR,
 DATE_OF_BIRTH DATE,
 ESCAPE_ATTEMPTS INT,
 NEUTERED BOOLEAN,
 WEIGHT_KG DECIMAL
 );

ALTER TABLE ANIMALS
ADD SPECIES VARCHAR;

