/* Database schema to keep the structure of entire database. */
CREATE TABLE ANIMALS (
 ID INT,
 NAME VARCHAR,
 DATE_OF_BIRTH DATE,
 ESCAPE_ATTEMPTS INT,
 NEUTERED BOOLEAN,
 WEIGHT_KG DECIMAL
 );

ALTER TABLE ANIMALS
ADD SPECIES VARCHAR;

CREATE TABLE OWNERS(
  ID INT GENERATED ALWAYS AS IDENTITY,
  FULL_NAME VARCHAR,
  AGE INT,
  PRIMARY KEY(ID)
);

CREATE TABLE SPECIES (
  ID INT GENERATED ALWAYS AS IDENTITY,
  NAME VARCHAR
);

ALTER TABLE SPECIES
ADD PRIMARY KEY(ID);

ALTER TABLE ANIMALS
ALTER COLUMN ID
SET NOT NULL;

ALTER TABLE ANIMALS
ALTER COLUMN ID
ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE ANIMALS
ADD PRIMARY KEY(ID);

ALTER TABLE SPECIES
ADD PRIMARY KEY(ID);

ALTER TABLE ANIMALS
DROP COLUMN SPECIES;

ALTER TABLE ANIMALS
ADD COLUMN SPECIES_ID INT;


ALTER TABLE ANIMALS
ADD CONSTRAINT CONSTRAINT_FKEY
FOREIGN KEY(SPECIES_ID)
REFERENCES SPECIES(ID)
ON DELETE CASCADE;

ALTER TABLE ANIMALS
ADD COLUMN OWNER_ID INT;

ALTER TABLE ANIMALS
ADD CONSTRAINT CONSTRAINT_OWNERS_FKEY
FOREIGN KEY(OWNER_ID)
REFERENCES OWNERS(ID)
ON DELETE CASCADE;